name: Sports Fan
favicon: null
layout_spectrum: 0.89449
typography_spectrum: 0.25919
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6875
  lightness: 0.15161664923653007
  saturation: 0.25
  rhythmicContrast: 0.6912439279258251
purpose: []
